Added Entities and Updated UserDataAccessObject
CSC207-fiveguys/music-java-app pull request #2
Opened 2023-11-06 03:38 UTC by HussainE4

Added classes and interfaces for our main entities (User, Track, Playlist, Artist) based on the proposed entities from our proposal. Up till now, each class only has getter methods. Also updated the User DataAccessObject (will definitely need another one for the spotify stuff). Instead of storing usernames and passwords, we now keep usernames and users. 

NOTE: We are not actually storing the data anywhere, it is just added to the dictionary. Need to add data persistence with json files

2023-11-06 03:47 UTC, skrukwa commented on src/app/Main.java
> +        UserDataAccessObject UserDataAccessObject = new UserDataAccessObject(new UserFactory());
views do not interact with DAOs

only use case interactors interact with DAOs

2023-11-06 03:48 UTC, skrukwa commented on src/data_access/UserDataAccessObject.java
> +    private UserFactory userFactory;
should be final?

2023-11-06 03:53 UTC, skrukwa commented on src/data_access/UserDataAccessObject.java
> +    public User getUser(String username){return users.get(username);}
does not follow Google Java Style Guide 4.1.2

2023-11-06 03:57 UTC, skrukwa commented on src/entities/CommonUser.java
> +public class CommonUser implements User{
Google Java Style Guide 4.6.2

2023-11-06 03:59 UTC, skrukwa commented on src/entities/CommonUser.java
> +    private final String name;
should use "username" and "getUsername", not to be confused with a users given name or government name

2023-11-06 04:02 UTC, skrukwa commented on src/entities/Track.java
> +
add "isExplicit()" method

2023-11-06 04:02 UTC, skrukwa commented on src/entities/Track.java
> +
4.6.1 Google Java Style Guide

2023-11-06 04:03 UTC, skrukwa commented on src/entities/CommonTrack.java
> +
fields should all be final

2023-11-06 04:03 UTC, skrukwa commented on src/entities/CommonTrack.java
> +
add "final boolean explicit"

2023-11-06 04:05 UTC, skrukwa commented on src/entities/CommonPlaylist.java
> +    private final User user;
use more descriptive (SCREAMING) "owner" field instead of "user"

2023-11-06 04:07 UTC, skrukwa requested changes
see comments, and ideally submit PRs using the template (even if all boxes are not check marked)

2023-11-06 05:10 UTC, HussainE4 commented on src/app/Main.java
> +        UserDataAccessObject UserDataAccessObject = new UserDataAccessObject(new UserFactory());
Correction: This is given to the UseCaseFactory which uses it when creating Controllers

2023-11-06 20:48 UTC, skrukwa requested changes
you still have comments from my first request that were not resolved. also please change  getExplicit to isExplicit for Track

2023-11-08 03:09 UTC, skrukwa approved these changes

2023-11-08 03:10 UTC, merged