Implemented login_new_signup
CSC207-fiveguys/music-java-app pull request #3
Opened 2023-11-06 16:40 UTC by bryjjch

Implemented login_new_signup

2023-11-06 19:12 UTC, HussainE4 commented on src/services/login_new_signup/LoginNewSignupOutputData.java
> +    }
Should remove the output data class instead of passing around an empty class

2023-11-06 19:17 UTC, HussainE4 commented on src/services/login_new_signup/LoginNewSignupPresenter.java
> +        viewManagerModel.firePropertyChanged();
If this is the usecase that goes to the login, shouldn't it set the active view to be the login view?

2023-11-06 19:18 UTC, HussainE4 commented on src/services/login_new_signup/LoginNewSignupInteractor.java
> +        LoginNewSignupOutputData loginNewSignupOutputData = new LoginNewSignupOutputData();
Should not have to create an empty class if there is no output data

2023-11-06 19:22 UTC, HussainE4 commented
Made some comments, mostly regarding the usage of the empty OutputData class that was being used.

2023-11-06 20:43 UTC, skrukwa requested changes

2023-11-06 20:43 UTC, skrukwa commented on src/services/login_new_signup/LoginNewSignupInputBoundary.java
> +    void initiateSignupProcess();
use "execute()" naming to stay consistent with other use cases

2023-11-07 11:28 UTC, bryjjch commented
I also removed OutputData InputData and Data Access but i forgot to mention in my commit message sorry :(

2023-11-08 04:12 UTC, umututku03 approved these changes

2023-11-08 04:12 UTC, umututku03 commented on src/services/login_new_signup/LoginNewSignupController.java
> +  public void goToSignup() {
it could be good to rephrase it as prepareSuccessView()

2023-11-11 04:31 UTC, bryjjch commented on src/services/login_new_signup/LoginNewSignupController.java
> +  public void goToSignup() {
changed

2023-11-13 15:33 UTC, skrukwa approved these changes

2023-11-13 15:37 UTC, merged