Implemented Abort Signup (Go to Login)
CSC207-fiveguys/music-java-app pull request #4
Opened 2023-11-06 17:10 UTC by bryjjch

description: Implemented Abort Signup (Go to Login)

---

- [ ] only docs were changed, the checklist below is left unchecked as it is not relevant

checklist:

- [ ] coding style (conforms to Google Java Style Guide) 
- [ ] especially follows section 7 (Javadoc is present for every public class, public or protected member)
- [ ] especially follows section 4.6 (Multiple consecutive blank lines are not encouraged).
- [ ] correctness (follows CA and SOLID, is a reasonable and not overly complicated solution, etc.)
- [ ] tests (contains tests with reasonable coverage)
- [ ] description of pull request is clear, consise, and reasonably detailed

2023-11-06 18:47 UTC, HussainE4 commented on src/services/signup_abort/SignupAbortInteractor.java
> +    ) {
Please check if this matches the Java Style Guide

2023-11-06 18:56 UTC, HussainE4 commented on src/services/signup_abort/SignupAbortInteractor.java
> +        userPresenter.presentLoginView(signupAbortOutputData);
Do we even need an output data class for this use case. I saw that Output data was empty class so maybe it'd be cleaner to just remove it.

2023-11-06 19:07 UTC, HussainE4 commented on src/services/signup_abort/SignupAbortOutputData.java
>  }
Instead of empty class, we could remove this

2023-11-06 20:45 UTC, skrukwa commented on src/services/signup_abort/SignupAbortOutputData.java
>  }
yes delete the file

2023-11-06 20:46 UTC, skrukwa requested changes

2023-11-06 20:46 UTC, skrukwa commented on src/services/signup_abort/SignupAbortInputBoundary.java
> +    void initiateLoginProcess();
use "execute()" name to be consistent with all other use cases

2023-11-08 04:10 UTC, umututku03 approved these changes

2023-11-08 04:10 UTC, umututku03 commented on src/services/signup_abort/SignupAbortController.java
> +  public void goToLogin() {
It could be good to rephrase it as prepareSuccessView()

2023-11-09 00:05 UTC, HussainE4 commented on src/services/signup_abort/SignupAbortController.java
> +  public void goToLogin() {
I agree as that is what we are using for the other use cases

2023-11-11 04:29 UTC, bryjjch commented on src/services/signup_abort/SignupAbortController.java
> +  public void goToLogin() {
Ok I changed it

2023-11-13 16:41 UTC, skrukwa approved these changes

2023-11-13 16:41 UTC, merged