Implementing LoginComplete Service
CSC207-fiveguys/music-java-app pull request #5
Opened 2023-11-08 04:04 UTC by umututku03

I have implemented the LogInComplete Use-Case, allowing registered users in our database to access and utilize all the services offered by our application.

## Motivation and Context

To utilize the full range of services and use-cases our app offers, users are required to log in. Consequently, it is essential to develop both the complete login use-case and its corresponding CA Engine components.

## Your Changes

I have successfully implemented all the components, including interface adapters and more, in alignment with the principles of Clean Architecture and SOLID.

**Type of change** (select all that apply):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Refactoring (internal change to codebase, without changing functionality)
- [ ] Test update (change that modifies or updates tests only)
- [ ] Documentation update (change that modifies or updates documentation only)
- [ ] Other (please specify):

## Testing

## Questions and Comments (if applicable)

## Checklist

- [X] I have performed a self-review of my own code.
- [ ] I have added tests for my changes. 
- [ ] Coverage tests
- [ ] Coding style (conforms to Google Java Style Guide)
- [ ] Especially follows section 7 (Javadoc is present for every public class, public or protected member)
- [ ] Especially follows section 4.6 (Multiple consecutive blank lines are not encouraged)
- [X] Correctness (follows CA and SOLID, is a reasonable and not overly complicated solution, etc.)
- [X] Description of pull request is clear, consise, and reasonably detailed

2023-11-08 04:14 UTC, bryjjch requested changes
Need to figure out setting errors.

2023-11-08 04:14 UTC, bryjjch commented on src/services/login_complete/LoginCompletePresenter.java
It would be wise to do something similar to loginstates/signupstates.

2023-11-09 00:00 UTC, HussainE4 requested changes
There a few Java Style issues that should be fixed; the UserDataAccessObject should implement the LoginCompleteUserDataAccessInterface and method names should be altered. Also, review the message regarding States

2023-11-20 14:47 UTC, HussainE4 approved these changes
works

2023-11-20 15:16 UTC, skrukwa approved these changes
lgtm

2023-11-20 15:17 UTC, merged